### ISSUE TITLE
Casanovo skipping spectra unexpectedly

### ISSUE THREAD

**Issue by temana-short** [Noble-Lab/casanovo#188]
I noticed when running Casanovo (3.3.0) on a spectra file with 20,000+ spectra (all with charge states 2+, 3+, or 4+), that I only got ~16000 PSMs. The first example of such is:

```
MASS=Monoisotopic
BEGIN IONS
TITLE=File10003 Spectrum1 scans: 1344
PEPMASS=445.12002 0.00000
CHARGE=4+
RTINSECONDS=474
SCANS=1344
149.02325 25003.7
167.05542 8641.78
359.02704 10051.9
360.02768 9059.18
361.02594 34899.6
362.02573 8862.7
END IONS
```

To try and identify the problem, I also tried other variants of this spectrum including using a `config.yaml` with `min_peptide_len: 1` and the below spectra, but no PSMs were identified for any of these spectra.

```
MASS=Monoisotopic
BEGIN IONS
PEPMASS=445.12002
CHARGE=4+
SCANS=1344
149.02325 25003.7
167.05542 8641.78
359.02704 10051.9
360.02768 9059.18
361.02594 34899.6
362.02573 8862.7
END IONS
```

I'm hoping to know why these spectra don't have Casanovo PSMs. Any help would be appreciated,
Temana

**Comment by bittremieux** [comment]
I can't reproduce this issue. A clean install of Casanovo 3.3 predicts peptide `REEEREEEEEKER` for this spectrum. Although with so few peaks in the spectra, it won't be possible to get accurate predictions.

Can you share the full Casanovo log file?

**Comment by temana-short** [comment]
Hi bittremieux,

Here is a link to the spectra file and output files (including Casanovo log file):
https://unisyd-my.sharepoint.com/:f:/g/personal/temana_short_sydney_edu_au/Eh5H3O0rLFZOoEkfitGhZY4BA7uy8ixzOlYLEC3QxQw13g 
password: casanovo

One thing to note is that the spectra file the one spectrum repeated 8 times (just to prevent the case where a CPU has zero spectra, which results in an error).

Thanks for looking at this,
Temana

**Comment by temana-short** [comment]
Hi,

I have some new results relating to this problem, with all .mgf, .mztab, and .log files available:
https://unisyd-my.sharepoint.com/:f:/g/personal/temana_short_sydney_edu_au/Eh5H3O0rLFZOoEkfitGhZY4BA7uy8ixzOlYLEC3QxQw13g
password: casanovo

First, I tried to run the full spectra on two different university linux servers (both with GPUs) named "albona" and "verona". I noticed that the one spectrum mentioned in my previous post was successfully assigned a PSM when run on "verona", but not when run on "albona". In these tests, I used the `--output=casanovo_output` flag, and noticed that the `spectra_ref` column showed that "albona" had only odd numbered spectra had an assigned PSM, with some missing (e.g. index=23), whereas "verona" had only 3mod4 numbered spectra (3, 7, 11, 15, ...) with assigned PSMs, with none missing.

I then tried running the same tests, on both linux servers, without the `--output=casanovo_output` flag, and noticed that two .mztab PSM files were created (and two .log files). On "albona", the first .mztab file has even numbered spectra, and the second .mztab file has odd numbered spectra (still with the same spectra missing). On "verona", the first .mztab file has all 0mod4 numbered spectra (0, 4, 8, 12, ...), and the second .mztab file has all 3mod4 numbered spectra.

I'm overall confused about why the two linux servers are producing different results, and also not sure how to fix this. Any help would be appreciated,
Temana

**Comment by wsnoble** [comment]
Does anyone know if this problem arises with the latest (unreleased) version of Casanovo?  Temana, can you pip install version 6299bd2 and see if the problem is still there?

` pip install git+https://github.com/Noble-Lab/casanovo.git@6299bd2`

**Comment by temana-short** [comment]
I've just run the latest (unreleased) version of Casanovo, and had a RuntimeError relating to Spec2Pep, details in the log file below. Specifically, I ran `bat server.log casanovo --mode=denovo --peak_path=../PXD008996/spectra_file.mgf`, where the `bat` command is used to run on the University Linux server.

[server.log](https://github.com/Noble-Lab/casanovo/files/11632138/temp.log)

**Comment by wsnoble** [comment]
Sorry, I reproduced this and then realized that the problem is likely because we fixed a bug in the sinusoidal encodings, so the old model weights are no longer compatible with the latest version. We will need to release a new version of Casanovo with new model weights in order to get this to work.

**Comment by bittremieux** [comment]
Hi Temana, your comment about different output on albona and verona is not that strange. I expect that albona has two GPUs and verona has four GPUs? Unfortunately Casanovo doesn't support _inference_ using multiple GPUs. In this case, the tasks are evenly divided over all GPUs, but the different output files overwrite each other. This is also mentioned in the documentation:
> **Warning**
> If you are running inference with Casanovo on a system that has multiple GPUs, it is necessary to restrict Casanovo to (maximum) a single GPU.
> For example, for CUDA-capable GPUs, GPU visibility can be controlled by setting the `CUDA_VISIBLE_DEVICES` shell variable.

Therefore, multiple GPUs are currently only supported to _train_ Casanovo.

So the latest report is a non-issue. Is it possible that this also accounts for the weird behavior that was initially observed?

**Comment by bittremieux** [comment]
@Melih is it possible that the Colab instance also had multiple GPUs and that might explain the issue? Your MGF works locally in any case.

**Comment by melihyilmaz** [comment]
@bittremieux I made sure Colab instance only uses a single GPU during inference and the output for my MGF is still missing.

**Comment by melihyilmaz** [comment]
@bittremieux v3.3.0 and v3.4.0

**Comment by melihyilmaz** [comment]
I re-ran Casanovo v3.5.0 for the sample spectrum I shared above, it still doesn't get a peptide. Output of the encoder seems to be all NaNs so this likely is tied to #186.

**Comment by xuel12** [comment]
I also experience this issue with v3.5. Casanovo skipped 2 out of ~50000 spectra in a MGF file, so that at the end the PSM_ID and index are all wrongly assigned.

**Comment by melihyilmaz** [comment]
@xuel12 thanks for reporting - you can still use the `spectra_ref` column in mzTab to get the correct index for PSMs.

**Comment by xuel12** [comment]
Thanks for pointing that out. I also tested the same input with version 3.4 using CPU only desktop, there was no skipping issue. When using GPU, both v3.4 and v3.5 skipped spectrum.

**Comment by melihyilmaz** [comment]
This issue seems to be resolved with the latest PyTorch release v2.10 - locally there were no skipped PSMs in the sample mgf file. You can upgrade your PyTorch to the latest or do a fresh install of Casanovo v3.5 which should automatically install PyTorch v2.10.
